# Classification config for chest X-ray pathology detection
path: ./data
train: images/train
val: images/val
test: images/test

# Classification classes - WHOLE IMAGE classification
names:
  0: normal
  1: clavicle_fracture  
  2: foreign_body

# Classification specific settings
task: classify
